export type AirportPlace = {
  city: string;
  country: string;
};

export const AIRPORT_PLACES: Record<string, AirportPlace> = {
  CYYZ: { city: "TORONTO", country: "CANADA" },
  CYTZ: { city: "TORONTO", country: "CANADA" },
  CYUL: { city: "MONTREAL", country: "CANADA" },
  CYOW: { city: "OTTAWA", country: "CANADA" },
  CYVR: { city: "VANCOUVER", country: "CANADA" },
  CYYC: { city: "CALGARY", country: "CANADA" },
  CYEG: { city: "EDMONTON", country: "CANADA" },
  CYWG: { city: "WINNIPEG", country: "CANADA" },
  CYHZ: { city: "HALIFAX", country: "CANADA" },
  CYYT: { city: "ST JOHNS", country: "CANADA" },
  CYQB: { city: "QUEBEC", country: "CANADA" },
  CYXE: { city: "SASKATOON", country: "CANADA" },
  CYQR: { city: "REGINA", country: "CANADA" },
  CYQT: { city: "THUNDER BAY", country: "CANADA" },
  CYTS: { city: "TIMMINS", country: "CANADA" },
  CYTH: { city: "THOMPSON", country: "CANADA" },
  CYFB: { city: "IQALUIT", country: "CANADA" },
  CYXY: { city: "WHITEHORSE", country: "CANADA" },
  CYXU: { city: "LONDON", country: "CANADA" },
  CYHM: { city: "HAMILTON", country: "CANADA" },
  CYKF: { city: "KITCHENER", country: "CANADA" },
  CYQG: { city: "WINDSOR", country: "CANADA" },
  CYAM: { city: "SAULT STE MARIE", country: "CANADA" },
  CYSB: { city: "SUDBURY", country: "CANADA" },
  CYFC: { city: "FREDERICTON", country: "CANADA" },
  CYQM: { city: "MONCTON", country: "CANADA" },
  CYSJ: { city: "SAINT JOHN", country: "CANADA" },
  CYCD: { city: "NANAIMO", country: "CANADA" },
  CYLW: { city: "KELOWNA", country: "CANADA" },
  CYYJ: { city: "VICTORIA", country: "CANADA" },
  CYMM: { city: "FORT MCMURRAY", country: "CANADA" },
  CYQU: { city: "GRANDE PRAIRIE", country: "CANADA" },
  CYXJ: { city: "FORT ST JOHN", country: "CANADA" },
  CYXS: { city: "PRINCE GEORGE", country: "CANADA" },
  CYXC: { city: "CRANBROOK", country: "CANADA" },
  CYXT: { city: "TERRACE", country: "CANADA" },
  CYKA: { city: "KAMLOOPS", country: "CANADA" },
  KJFK: { city: "NEW YORK", country: "USA" },
  KLGA: { city: "NEW YORK", country: "USA" },
  KEWR: { city: "NEWARK", country: "USA" },
  KHPN: { city: "WHITE PLAINS", country: "USA" },
  KORD: { city: "CHICAGO", country: "USA" },
  KDTW: { city: "DETROIT", country: "USA" },
  KSFO: { city: "SAN FRANCISCO", country: "USA" },
  KIAD: { city: "WASHINGTON", country: "USA" },
  KDCA: { city: "WASHINGTON", country: "USA" },
  KATL: { city: "ATLANTA", country: "USA" },
  KBNA: { city: "NASHVILLE", country: "USA" },
  KBUR: { city: "BURBANK", country: "USA" },
  KCVG: { city: "CINCINNATI", country: "USA" },
  KDAB: { city: "DAYTONA BEACH", country: "USA" },
  KDEN: { city: "DENVER", country: "USA" },
  KDFW: { city: "DALLAS", country: "USA" },
  KIAH: { city: "HOUSTON", country: "USA" },
  KLAX: { city: "LOS ANGELES", country: "USA" },
  KMIA: { city: "MIAMI", country: "USA" },
  KMCO: { city: "ORLANDO", country: "USA" },
  KMHT: { city: "MANCHESTER", country: "USA" },
  KMSP: { city: "MINNEAPOLIS", country: "USA" },
  KOAK: { city: "OAKLAND", country: "USA" },
  KPHL: { city: "PHILADELPHIA", country: "USA" },
  KPHX: { city: "PHOENIX", country: "USA" },
  KRDU: { city: "RALEIGH", country: "USA" },
  KSEA: { city: "SEATTLE", country: "USA" },
  KLAS: { city: "LAS VEGAS", country: "USA" },
  KSAN: { city: "SAN DIEGO", country: "USA" },
  KSJC: { city: "SAN JOSE", country: "USA" },
  KSMF: { city: "SACRAMENTO", country: "USA" },
  KPDX: { city: "PORTLAND", country: "USA" },
  KSLC: { city: "SALT LAKE CITY", country: "USA" },
  KSTL: { city: "ST LOUIS", country: "USA" },
  KMCI: { city: "KANSAS CITY", country: "USA" },
  KAUS: { city: "AUSTIN", country: "USA" },
  KSAT: { city: "SAN ANTONIO", country: "USA" },
  KHOU: { city: "HOUSTON", country: "USA" },
  KDAL: { city: "DALLAS", country: "USA" },
  KCLT: { city: "CHARLOTTE", country: "USA" },
  KFLL: { city: "FORT LAUDERDALE", country: "USA" },
  KTPA: { city: "TAMPA", country: "USA" },
  KJAX: { city: "JACKSONVILLE", country: "USA" },
  KMSY: { city: "NEW ORLEANS", country: "USA" },
  KMEM: { city: "MEMPHIS", country: "USA" },
  KIND: { city: "INDIANAPOLIS", country: "USA" },
  KCLE: { city: "CLEVELAND", country: "USA" },
  KCMH: { city: "COLUMBUS", country: "USA" },
  KPIT: { city: "PITTSBURGH", country: "USA" },
  KBDL: { city: "HARTFORD", country: "USA" },
  KPVD: { city: "PROVIDENCE", country: "USA" },
  KALB: { city: "ALBANY", country: "USA" },
  KBUF: { city: "BUFFALO", country: "USA" },
  KROC: { city: "ROCHESTER", country: "USA" },
  KSYR: { city: "SYRACUSE", country: "USA" },
  KGRR: { city: "GRAND RAPIDS", country: "USA" },
  KMKE: { city: "MILWAUKEE", country: "USA" },
  KOMA: { city: "OMAHA", country: "USA" },
  KOKC: { city: "OKLAHOMA CITY", country: "USA" },
  KTUL: { city: "TULSA", country: "USA" },
  KABQ: { city: "ALBUQUERQUE", country: "USA" },
  KBOS: { city: "BOSTON", country: "USA" },
  KBWI: { city: "BALTIMORE", country: "USA" },
  KMDW: { city: "CHICAGO", country: "USA" },
  PHNL: { city: "HONOLULU", country: "USA" },
  PANC: { city: "ANCHORAGE", country: "USA" },
  TJSJ: { city: "SAN JUAN", country: "PUERTO RICO" },
  CUN: { city: "CANCUN", country: "MEXICO" },
  MMUN: { city: "CANCUN", country: "MEXICO" },
  MMMX: { city: "MEXICO CITY", country: "MEXICO" },
  MMGL: { city: "GUADALAJARA", country: "MEXICO" },
  MMMY: { city: "MONTERREY", country: "MEXICO" },
  MMSD: { city: "SAN JOSE DEL CABO", country: "MEXICO" },
  MMPR: { city: "PUERTO VALLARTA", country: "MEXICO" },
  MMMD: { city: "MERIDA", country: "MEXICO" },
  MMTJ: { city: "TIJUANA", country: "MEXICO" },
  LPPT: { city: "LISBON", country: "PORTUGAL" },
  EGLL: { city: "LONDON", country: "UK" },
  LFPG: { city: "PARIS", country: "FRANCE" },
  EDDF: { city: "FRANKFURT", country: "GERMANY" }
};

export function airportPlaceLabel(code?: string) {
  if (!code) return "UNKNOWN";
  const place = AIRPORT_PLACES[code.toUpperCase()];
  if (!place) return "UNKNOWN";
  return `${place.city} ${place.country}`;
}
